Test commit

diff --git a/.husky/_/pre-commit b/.husky/_/pre-commit
--- a/.husky/_/pre-commit
+++ b/.husky/_/pre-commit
@@ -1,2 +1,12 @@
-#!/usr/bin/env sh
-. "${0%/*}/h"
+#!/bin/sh
+
+# Run linting and formatting
+npm run lint:fix
+npm run format
+
+# Run tests
+npm test
+
+# If everything passes, allow the commit
+# If any of the commands fail, the commit will be aborted
+npm run commitlint || true
